import '../styles/globals.css';
import Layout from "../components/Layout";
import Head from "next/head";
import "../styles/global2.scss"
import ClineSideRendering from "../components/CSRandSSR/clineSideRendering";
import ServerSideRendering from "../components/CSRandSSR/serverSideRendering";

function MyApp({Component, pageProps}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
                      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
                      crossorigin="anonymous"/>
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </>

    )
}

export default MyApp
