import '../styles/globals.css';
import Head from "next/head";
import "../styles/global2.scss"
import { NextSeo } from "next-seo";
import React from "react";
import {Provider} from "next-auth/client";

function MyApp({Component, pageProps}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
                      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
                      crossorigin="anonymous"/>
            </Head>
            <NextSeo
                title="next js"
                titleTemplate="Dovudhon Husanov"
                description="this is for tutorial"
                facebook="https://www.facebook.com/dovudhonkhusanov/"
                twitter="https://twitter.com/dovudhonhusanov"
            />
            
            <Provider session={pageProps.session}>
                {/*<Layout>*/}
                    <Component {...pageProps} />
                {/*</Layout>*/}
            </Provider>
        </>

    )
}

export default MyApp
